/*
 * Copyright (C) 2011 NATSRL @ UMD (University Minnesota Duluth, US) and
 * Software and System Laboratory @ KNU (Kangwon National University, Korea) 
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package edu.umn.natsrl.ticas;

import edu.umn.natsrl.infra.TMO;

/**
 *
 * @author Chongmyung Park
 */
public class ClearCacheDialog extends javax.swing.JDialog {
    
    private TMO tmo = TMO.getInstance();
    
    /** Creates new form ClearCacheDialog */
    public ClearCacheDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTrafficDataCache = new javax.swing.JButton();
        btnDetectorDataCache = new javax.swing.JButton();
        btnDetectorFailCache = new javax.swing.JButton();
        btnAllCache = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TICAS : Cache Cleaner");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clear Cache", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        btnTrafficDataCache.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnTrafficDataCache.setText("Traffic Data Cache");
        btnTrafficDataCache.setPreferredSize(new java.awt.Dimension(165, 25));
        btnTrafficDataCache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrafficDataCacheActionPerformed(evt);
            }
        });

        btnDetectorDataCache.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnDetectorDataCache.setText("Detector Data Cache");
        btnDetectorDataCache.setPreferredSize(new java.awt.Dimension(165, 25));
        btnDetectorDataCache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetectorDataCacheActionPerformed(evt);
            }
        });

        btnDetectorFailCache.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnDetectorFailCache.setText("Detector Fail Cache");
        btnDetectorFailCache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetectorFailCacheActionPerformed(evt);
            }
        });

        btnAllCache.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnAllCache.setText("All Cache");
        btnAllCache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllCacheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTrafficDataCache, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(btnDetectorDataCache, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(btnDetectorFailCache, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(btnAllCache, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTrafficDataCache, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetectorDataCache, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetectorFailCache, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAllCache, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrafficDataCacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrafficDataCacheActionPerformed
        tmo.clearTrafficDataCache();
    }//GEN-LAST:event_btnTrafficDataCacheActionPerformed

    private void btnDetectorDataCacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetectorDataCacheActionPerformed
        tmo.clearDetectorDataCache();
    }//GEN-LAST:event_btnDetectorDataCacheActionPerformed

    private void btnDetectorFailCacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetectorFailCacheActionPerformed
        tmo.clearDetectorFailCache();
    }//GEN-LAST:event_btnDetectorFailCacheActionPerformed

    private void btnAllCacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllCacheActionPerformed
        tmo.clearAllCache();
    }//GEN-LAST:event_btnAllCacheActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllCache;
    private javax.swing.JButton btnDetectorDataCache;
    private javax.swing.JButton btnDetectorFailCache;
    private javax.swing.JButton btnTrafficDataCache;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
