/*
 * Copyright (C) 2011 NATSRL @ UMD (University Minnesota Duluth, US) and
 * Software and System Laboratory @ KNU (Kangwon National University, Korea) 
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package edu.umn.natsrl.sfim;

import edu.umn.natsrl.util.FileHelper;
import edu.umn.natsrl.util.StringOutputStream;
import java.awt.Point;
import java.io.IOException;
import java.io.PrintStream;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Chongmyung Park (chongmyung.park@gmail.com)
 */
public class RunningDialog extends javax.swing.JDialog {
    
    static boolean expanded = true;
    
    PrintStream outBack;
    PrintStream errBack;
    StringOutputStream sos;
            
    /** Creates new form RunningDialog */
    public RunningDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        
        outBack = System.out;
        errBack = System.err;
        sos = new StringOutputStream(tbxLog);
        
        Point loc = this.getLocation();
        loc.y -= 200;
        this.setLocation(loc);

        if(!RunningDialog.expanded) {
            hideLog();
        } else {
            showLog();
        }
        

    }

    private void showLog()
    {
        this.tbxLog.setVisible(true);
        this.setSize(625, 190);
        lbExpand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/umn/natsrl/sfim/resources/collapse_icon.png")));                
        RunningDialog.expanded = true;
        System.setOut(new PrintStream(sos));
        System.setErr(new PrintStream(sos));        
    }
    
    private void hideLog()
    {
        this.tbxLog.setVisible(false);
        this.setSize(625, 60);        
        lbExpand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/umn/natsrl/sfim/resources/expand_icon.png")));        
        RunningDialog.expanded = false;
        System.setOut(outBack);
        System.setErr(errBack);        
    }

    
    public void close(double second)
    {
        Timer t = new Timer();
        t.schedule(new TimerTask() {

            @Override
            public void run() {
                dispose();
            }
        }, (int)second*1000);
    }
    
    @Override
    public void dispose()
    {
        System.setOut(outBack);
        System.setErr(errBack);
        try {
            FileHelper.writeTextFile(tbxLog.getText(), "log.txt");
        } catch (IOException ex) {
            
        }
        super.dispose();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbxLog = new javax.swing.JTextArea();
        lbExpand = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/umn/natsrl/sfim/resources/running.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 24));
        jLabel2.setText("Please Wait ...");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 15, -1, -1));

        tbxLog.setColumns(20);
        tbxLog.setEditable(false);
        tbxLog.setLineWrap(true);
        tbxLog.setRows(5);
        tbxLog.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(tbxLog);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 600, 120));

        lbExpand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/umn/natsrl/sfim/resources/expand_icon.png"))); // NOI18N
        lbExpand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExpandMouseClicked(evt);
            }
        });
        jPanel1.add(lbExpand, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbExpandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExpandMouseClicked
        if(RunningDialog.expanded) hideLog();
        else showLog();
    }//GEN-LAST:event_lbExpandMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RunningDialog dialog = new RunningDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbExpand;
    private javax.swing.JTextArea tbxLog;
    // End of variables declaration//GEN-END:variables

}
