/*
 * Copyright (C) 2011 NATSRL @ UMD (University Minnesota Duluth, US) and
 * Software and System Laboratory @ KNU (Kangwon National University, Korea) 
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package edu.umn.natsrl.infra.section;

import edu.umn.natsrl.infra.InfraConstants;
import edu.umn.natsrl.infra.infraobjects.RNode;
import edu.umn.natsrl.infra.Section;
import java.awt.Frame;
import java.io.File;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Chongmyung Park (chongmyung.park@gmail.com)
 */
public class SectionSaveDialog extends javax.swing.JDialog {

    private List<RNode> section;
    public boolean isSaved = false;
    private ISectionChanged changeListener;
    
    public SectionSaveDialog(Frame parent, List<RNode> section) {
        super(parent, true);
        initComponents();        
        this.section = section;
        if(this.section == null || this.section.isEmpty()) {
            System.out.println("No rnodes in section");
        }
        
    }
    
    private void saveSection()
    {
        String name = this.tbxSectionName.getText();
        String desc = this.tbxSectionDesc.getText();
        if(!checkName(name)) return;
        Section s = new Section(name, desc);
        s.addRNode(this.section);
        
        try {
            s.save();
            this.isSaved = true;
            
            if(changeListener != null) changeListener.sectionChanged(SectionChangedStatus.CREATED);
            this.dispose();
        } catch(Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Fail to save section");
            this.dispose();
        }
    }

    private boolean checkName(String name)
    {
        if(name.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Fail : Section name is required");
            return false;
        }
        if(name.length() > 128) {
            JOptionPane.showMessageDialog(rootPane, "Fail : Section name is long. (128 characters limit)");
            return false;
        }
        String eName = Section.getCacheFileName(name);
        if(eName == null) {
            JOptionPane.showMessageDialog(rootPane, "Fail : MD5 algorithm does not exist!!");
            return false;            
        }
        String filename = InfraConstants.SECTION_DIR + File.separator + eName;
        File targetFile = new File(filename);
        if(targetFile.exists())
        {
            int res = JOptionPane.showConfirmDialog(rootPane, "Section name already exists. Overwrite the section?");
            if(res > 0) return false;
        }
        return true;
    }

    public void setChangeListener(ISectionChanged changeListener) {
        this.changeListener = changeListener;
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbxSectionName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbxSectionDesc = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Save Section");

        jLabel2.setText("Route Name");

        jLabel3.setText("Description");

        tbxSectionDesc.setColumns(20);
        tbxSectionDesc.setRows(5);
        jScrollPane1.setViewportView(tbxSectionDesc);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(tbxSectionName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxSectionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        saveSection();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tbxSectionDesc;
    private javax.swing.JTextField tbxSectionName;
    // End of variables declaration//GEN-END:variables

}
