/*
 * Copyright (C) 2011 NATSRL @ UMD (University Minnesota Duluth, US) and
 * Software and System Laboratory @ KNU (Kangwon National University, Korea) 
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package edu.umn.natsrl.infraviewer;

import java.awt.BorderLayout;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Chongmyung Park
 */
public class InfraViewerFrame extends javax.swing.JFrame {
    
    InfraViewerPanel ivp;
            
    /** Creates new form InfraViewerFrame */
    public InfraViewerFrame() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/edu/umn/natsrl/infraviewer/resources/mapmarker.png")).getImage());        
        ivp = new InfraViewerPanel(this);
        this.getContentPane().setLayout(new BorderLayout());
        this.getContentPane().add(ivp);
    }
    
    public void init() {
        ivp.init();
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemUpdateGeo = new javax.swing.JMenuItem();
        menuItemExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuItemSectionCreator = new javax.swing.JMenuItem();
        menuItemDistance = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Infra Viewer - NATSRL");

        menuFile.setText("File");

        menuItemUpdateGeo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuItemUpdateGeo.setText("Update geometry data");
        menuItemUpdateGeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUpdateGeoActionPerformed(evt);
            }
        });
        menuFile.add(menuItemUpdateGeo);

        menuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuFile.add(menuItemExit);

        jMenuBar1.add(menuFile);

        menuEdit.setText("Edit");

        menuItemSectionCreator.setText("Section Creator");
        menuItemSectionCreator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSectionCreatorActionPerformed(evt);
            }
        });
        menuEdit.add(menuItemSectionCreator);

        menuItemDistance.setText("RNode Distance");
        menuItemDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDistanceActionPerformed(evt);
            }
        });
        menuEdit.add(menuItemDistance);

        jMenuBar1.add(menuEdit);

        menuHelp.setText("Help");
        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 897, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemUpdateGeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUpdateGeoActionPerformed
        new File("infra.dat").delete();
        JOptionPane.showMessageDialog(rootPane, "Run infra viewer again!!");
        System.exit(0);
}//GEN-LAST:event_menuItemUpdateGeoActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        System.exit(0);
}//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemSectionCreatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSectionCreatorActionPerformed
        SectionCreatorFrame sc = new SectionCreatorFrame();
        sc.setLocationRelativeTo(this);
        sc.setVisible(true);
}//GEN-LAST:event_menuItemSectionCreatorActionPerformed

    private void menuItemDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDistanceActionPerformed
        RNodeDistanceDialog rdd = new RNodeDistanceDialog(this, false);
        rdd.setLocationRelativeTo(this);
        rdd.setVisible(true);
}//GEN-LAST:event_menuItemDistanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new InfraViewerFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemDistance;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemSectionCreator;
    private javax.swing.JMenuItem menuItemUpdateGeo;
    // End of variables declaration//GEN-END:variables
}
