/*
 * Copyright (C) 2011 NATSRL @ UMD (University Minnesota Duluth) and
 * Software and System Laboratory @ KNU (Kangwon National University, Korea) 
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package edu.umn.natsrl.map;

import edu.umn.natsrl.infra.Section;
import edu.umn.natsrl.map.InfraPoint.MarkerType;
import edu.umn.natsrl.weatherRWIS.site.Site;
import java.awt.Frame;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.swingx.JXMapViewer;

/**
 *
 * @author Soobin Jeon <j.soobin@gmail.com>
 */
public class InfraRWISMenu extends javax.swing.JPanel {
        private Frame parents;
        private InfraPoint ip;
        private MapHelper map;
        private Section section;
        private Site newsite;
        /**
         * Creates new form InfraRWISMenu
         */
        public InfraRWISMenu(Site _site, java.awt.Frame parent, MapHelper _map, InfraPoint _ip, Section _section) {
                initComponents();
                parents = parent;
                map = _map;
                ip = _ip;
                section = _section;
                newsite = _site;
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                popupMenuRWIS = new javax.swing.JPopupMenu();
                SetMainSite = new javax.swing.JMenuItem();

                popupMenuRWIS.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                popupMenuRWISMouseClicked(evt);
                        }
                });

                SetMainSite.setText("SetMainSite");
                SetMainSite.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                SetMainSiteActionPerformed(evt);
                        }
                });
                popupMenuRWIS.add(SetMainSite);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
                );
        }// </editor-fold>//GEN-END:initComponents

        private void popupMenuRWISMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popupMenuRWISMouseClicked
                // TODO add your handling code here:
        }//GEN-LAST:event_popupMenuRWISMouseClicked

        private void SetMainSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetMainSiteActionPerformed
                // TODO add your handling code here:
                ReplaceSection();
                map.repaint();
                setPopup(false);
        }//GEN-LAST:event_SetMainSiteActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JMenuItem SetMainSite;
        private javax.swing.JPopupMenu popupMenuRWIS;
        // End of variables declaration//GEN-END:variables

        void setPopup(int sx, int sy) {
                popupMenuRWIS.show(parents, sx, sy);
        }

        void setPopup(boolean b) {
                popupMenuRWIS.setVisible(b);
        }

        private void ReplaceSection() {
                ip.setMarkerType(MarkerType.SITEON);
                
                Site csite = section.getSite();
                for(InfraPoint p : map.getPoints()){
                        if(p.getSite() != null){
                                if(p.getSite().getID() == csite.getID()){
                                        p.setMarkerType(MarkerType.SITENONE);
                                }
                        }
                }
                section.setSite(newsite);
                try {
                        section.save();
                } catch (Exception ex) {
                        ex.printStackTrace();
                }
        }
}
